site_name: Home Semiconductor Wiki
site_url: https://homesemi.wiki/
repo_url: https://github.com/LQ1234/homesemiwiki
edit_uri: edit/main/docs/

theme:
    name: material
nav:
    - Home: index.md
    - About: about.md
